### ISSUE TITLE
Need to use .gitignore on Library folder, etc

### ISSUE THREAD

**Issue by yuheho7749** [hanzemeng/Dummy_Project#2]
Including the library folder will cause lots of version control errors. In other words, the Library folder, temp, build folders, etc are used by unity/unity hub to run on your machine only. Tracking them causes lots of issues. I found the video below to be helpful regarding this issue.

https://youtu.be/TbdWXbRlPo0

PR #1 runs into this issue that different machines/Library folders have conflicts that cannot be resolved/causes the project to be corrupted

Edit: I don't know too much as well. I'll look more into it this weekend.

**Comment by crdgdr** [comment]
From Vicki: I found a .gitignore template for Unity projects and included it in my commit. Can't push right now since Zach haven't invited me to the repository

**Comment by yuheho7749** [comment]
Resolved
